INSERT INTO players (score, rank, stars, nickname, avatar_url) VALUES
(3, 1, 3, 'katara o avatar da Água', '../assets/katara.webp'),
(3, 1, 5, 'anonimo22', '../assets/anonimo22.jpg'),
(3, 1, 5, 'Botijão de gás cromado', '../assets/botijao.jpg'),
(3, 1, 5, 'Luladroid3000', '../assets/Luladroid3000.png'),
(3, 1, 5, 'CREATOR0110', '../assets/CREATOR0110.png'),
(3, 1, 5, 'Enigma_Hardcore2023', '../assets/Enigma_Hardcore2023.jpg'),
(3, 1, 5, 'CLT', '../assets/CLT.jpg'),
(3, 1, 5, '𝔪𝔢𝔫𝔦𝔫𝔬 𝔡𝔞 𝔳𝔦𝔩𝔞', '../assets/meninodavila.jpg'),
(3, 1, 5, 'Minecraft+Gravidade', '../assets/Minecraft+Gravidade.webp'),
(3, 1, 5, 'lokfn', '../assets/lokfn.png'),
(3, 1, 5, 'aldãobtos', '../assets/aldaobtos.jpg'),
(3, 1, 5, '𝔅𝔞𝔡𝔟𝔬𝔶𝔡𝔢𝔟𝔞𝔯𝔯𝔢𝔱𝔬𝔰', '../assets/badboy.jpg'),
(3, 1, 5, 'sonegador de imposto', '../assets/sonegadordeimposto.webp'),
(3, 1, 5, 'Paula Tejano', '../assets/PaulaTejano.png'),
(3, 1, 5, 'Thomas tur', '../assets/Thomastur.jpg'),
(3, 1, 5, '꧁𓆩BlackSwan𓆪꧂', '../assets/BlackSwan.png'),
(3, 1, 5, 'Scooby', '../assets/Scooby.png'),
(3, 1, 5, '😈😈', '../assets/evil_laugh.png'),
(3, 1, 5, 'nanamin', '../assets/nanamin.png'),
(3, 1, 5, 'oreia ou gaylherme', '../assets/oreia.jpg'),
(3, 1, 5, 'anonimo 8', '../assets/anonimo8.webp'),
(3, 1, 6, 'Japônes', '../assets/japones.jpg'),
(3, 1, 5, 'Pimpolho', '../assets/pimpolho.jpg');